#coding: utf8

RESULT_SUCCEED                      = 0
RESULT_FAILED                       = 1

RESULT_FAILED_ACCOUNT_INVALID       = 2
RESULT_FAILED_PASSWORD_INVALID      = 3
RESULT_FAILED_NO_LOGIN              = 4
RESULT_FAILED_NAME_EXISTED          = 5
RESULT_FAILED_PASSWORD_INVALID      = 6

