# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: constant.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='constant.proto',
  package='island',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x63onstant.proto\x12\x06island*a\n\x0bUpgradeType\x12\x0e\n\nNO_UPGRADE\x10\x00\x12\x14\n\x10MUST_UPGARDE_APP\x10\x01\x12\x16\n\x12SHOULD_UPGRADE_APP\x10\x02\x12\x14\n\x10UPGRADE_RESOURCE\x10\x03*<\n\x08GameType\x12\x08\n\x04G1X1\x10\x01\x12\x08\n\x04G1X2\x10\x02\x12\x08\n\x04G2X2\x10\x03\x12\x08\n\x04G3X0\x10\x04\x12\x08\n\x04G4X0\x10\x05*(\n\tForceType\x12\x0c\n\x08\x46_NORMAL\x10\x00\x12\r\n\tF_MISSILE\x10\x01*J\n\rForceMoveType\x12\x08\n\x04STAY\x10\x01\x12\x08\n\x04MOVE\x10\x02\x12\x08\n\x04RAID\x10\x03\x12\x10\n\x0cRAID_FAILURE\x10\x04\x12\t\n\x05STORM\x10\x05*A\n\nIslandType\x12\n\n\x06\x42_BORN\x10\x00\x12\x0c\n\x08\x42_NORMAL\x10\x01\x12\r\n\tB_MISSILE\x10\x02\x12\n\n\x06\x42_FORT\x10\x03* \n\x0b\x46ightResult\x12\x07\n\x03WIN\x10\x01\x12\x08\n\x04LOST\x10\x02*\xc1\x01\n\x0bPropertyKey\x12\x0b\n\x07P_SPEED\x10\x01\x12\x0c\n\x08P_SUPPLY\x10\x02\x12\x17\n\x13P_SUPPLY_MAX_TROOPS\x10\x03\x12\x13\n\x0fP_MISSILE_SPEED\x10\x04\x12\x14\n\x10P_MISSILE_SUPPLY\x10\x05\x12\x11\n\rP_FORT_RADIUS\x10\x06\x12\x11\n\rP_FORT_ATTACK\x10\x07\x12\x15\n\x11P_FORT_MAX_TROOPS\x10\x08\x12\x16\n\x12P_FORT_BORN_TROOPS\x10\tB\"\n\x14\x63om.box.island.protoB\x08\x43onstantH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_UPGRADETYPE = _descriptor.EnumDescriptor(
  name='UpgradeType',
  full_name='island.UpgradeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_UPGRADE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUST_UPGARDE_APP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHOULD_UPGRADE_APP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_RESOURCE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=26,
  serialized_end=123,
)
_sym_db.RegisterEnumDescriptor(_UPGRADETYPE)

UpgradeType = enum_type_wrapper.EnumTypeWrapper(_UPGRADETYPE)
_GAMETYPE = _descriptor.EnumDescriptor(
  name='GameType',
  full_name='island.GameType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='G1X1', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G1X2', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G2X2', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G3X0', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G4X0', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=125,
  serialized_end=185,
)
_sym_db.RegisterEnumDescriptor(_GAMETYPE)

GameType = enum_type_wrapper.EnumTypeWrapper(_GAMETYPE)
_FORCETYPE = _descriptor.EnumDescriptor(
  name='ForceType',
  full_name='island.ForceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='F_NORMAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='F_MISSILE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=187,
  serialized_end=227,
)
_sym_db.RegisterEnumDescriptor(_FORCETYPE)

ForceType = enum_type_wrapper.EnumTypeWrapper(_FORCETYPE)
_FORCEMOVETYPE = _descriptor.EnumDescriptor(
  name='ForceMoveType',
  full_name='island.ForceMoveType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STAY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAID', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAID_FAILURE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORM', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=229,
  serialized_end=303,
)
_sym_db.RegisterEnumDescriptor(_FORCEMOVETYPE)

ForceMoveType = enum_type_wrapper.EnumTypeWrapper(_FORCEMOVETYPE)
_ISLANDTYPE = _descriptor.EnumDescriptor(
  name='IslandType',
  full_name='island.IslandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='B_BORN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='B_NORMAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='B_MISSILE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='B_FORT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=305,
  serialized_end=370,
)
_sym_db.RegisterEnumDescriptor(_ISLANDTYPE)

IslandType = enum_type_wrapper.EnumTypeWrapper(_ISLANDTYPE)
_FIGHTRESULT = _descriptor.EnumDescriptor(
  name='FightResult',
  full_name='island.FightResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WIN', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOST', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=372,
  serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_FIGHTRESULT)

FightResult = enum_type_wrapper.EnumTypeWrapper(_FIGHTRESULT)
_PROPERTYKEY = _descriptor.EnumDescriptor(
  name='PropertyKey',
  full_name='island.PropertyKey',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='P_SPEED', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P_SUPPLY', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P_SUPPLY_MAX_TROOPS', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P_MISSILE_SPEED', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P_MISSILE_SUPPLY', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P_FORT_RADIUS', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P_FORT_ATTACK', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P_FORT_MAX_TROOPS', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P_FORT_BORN_TROOPS', index=8, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=407,
  serialized_end=600,
)
_sym_db.RegisterEnumDescriptor(_PROPERTYKEY)

PropertyKey = enum_type_wrapper.EnumTypeWrapper(_PROPERTYKEY)
NO_UPGRADE = 0
MUST_UPGARDE_APP = 1
SHOULD_UPGRADE_APP = 2
UPGRADE_RESOURCE = 3
G1X1 = 1
G1X2 = 2
G2X2 = 3
G3X0 = 4
G4X0 = 5
F_NORMAL = 0
F_MISSILE = 1
STAY = 1
MOVE = 2
RAID = 3
RAID_FAILURE = 4
STORM = 5
B_BORN = 0
B_NORMAL = 1
B_MISSILE = 2
B_FORT = 3
WIN = 1
LOST = 2
P_SPEED = 1
P_SUPPLY = 2
P_SUPPLY_MAX_TROOPS = 3
P_MISSILE_SPEED = 4
P_MISSILE_SUPPLY = 5
P_FORT_RADIUS = 6
P_FORT_ATTACK = 7
P_FORT_MAX_TROOPS = 8
P_FORT_BORN_TROOPS = 9


DESCRIPTOR.enum_types_by_name['UpgradeType'] = _UPGRADETYPE
DESCRIPTOR.enum_types_by_name['GameType'] = _GAMETYPE
DESCRIPTOR.enum_types_by_name['ForceType'] = _FORCETYPE
DESCRIPTOR.enum_types_by_name['ForceMoveType'] = _FORCEMOVETYPE
DESCRIPTOR.enum_types_by_name['IslandType'] = _ISLANDTYPE
DESCRIPTOR.enum_types_by_name['FightResult'] = _FIGHTRESULT
DESCRIPTOR.enum_types_by_name['PropertyKey'] = _PROPERTYKEY


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024com.box.island.protoB\010ConstantH\003'))
# @@protoc_insertion_point(module_scope)
