# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: constant.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='constant.proto',
  package='island',
  serialized_pb=_b('\n\x0e\x63onstant.proto\x12\x06island*a\n\x0bUpgradeType\x12\x0e\n\nNO_UPGRADE\x10\x00\x12\x14\n\x10MUST_UPGARDE_APP\x10\x01\x12\x16\n\x12SHOULD_UPGRADE_APP\x10\x02\x12\x14\n\x10UPGRADE_RESOURCE\x10\x03*\x1e\n\x08GameType\x12\x08\n\x04G2X2\x10\x01\x12\x08\n\x04G4X4\x10\x02*-\n\tForceType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03USA\x10\x01\x12\n\n\x06RUSSIA\x10\x02*J\n\rForceMoveType\x12\x08\n\x04STAY\x10\x01\x12\x08\n\x04MOVE\x10\x02\x12\x08\n\x04RAID\x10\x03\x12\x10\n\x0cRAID_FAILURE\x10\x04\x12\t\n\x05STORM\x10\x05*\'\n\nIslandType\x12\n\n\x06NORMAL\x10\x01\x12\r\n\tONLY_REST\x10\x02*\"\n\x0b\x46ightResult\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02\x42\"\n\x14\x63om.box.island.protoB\x08\x43onstantH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_UPGRADETYPE = _descriptor.EnumDescriptor(
  name='UpgradeType',
  full_name='island.UpgradeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_UPGRADE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUST_UPGARDE_APP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHOULD_UPGRADE_APP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_RESOURCE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=26,
  serialized_end=123,
)
_sym_db.RegisterEnumDescriptor(_UPGRADETYPE)

UpgradeType = enum_type_wrapper.EnumTypeWrapper(_UPGRADETYPE)
_GAMETYPE = _descriptor.EnumDescriptor(
  name='GameType',
  full_name='island.GameType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='G2X2', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G4X4', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=125,
  serialized_end=155,
)
_sym_db.RegisterEnumDescriptor(_GAMETYPE)

GameType = enum_type_wrapper.EnumTypeWrapper(_GAMETYPE)
_FORCETYPE = _descriptor.EnumDescriptor(
  name='ForceType',
  full_name='island.ForceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUSSIA', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=157,
  serialized_end=202,
)
_sym_db.RegisterEnumDescriptor(_FORCETYPE)

ForceType = enum_type_wrapper.EnumTypeWrapper(_FORCETYPE)
_FORCEMOVETYPE = _descriptor.EnumDescriptor(
  name='ForceMoveType',
  full_name='island.ForceMoveType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STAY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAID', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAID_FAILURE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORM', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=204,
  serialized_end=278,
)
_sym_db.RegisterEnumDescriptor(_FORCEMOVETYPE)

ForceMoveType = enum_type_wrapper.EnumTypeWrapper(_FORCEMOVETYPE)
_ISLANDTYPE = _descriptor.EnumDescriptor(
  name='IslandType',
  full_name='island.IslandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONLY_REST', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=280,
  serialized_end=319,
)
_sym_db.RegisterEnumDescriptor(_ISLANDTYPE)

IslandType = enum_type_wrapper.EnumTypeWrapper(_ISLANDTYPE)
_FIGHTRESULT = _descriptor.EnumDescriptor(
  name='FightResult',
  full_name='island.FightResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=321,
  serialized_end=355,
)
_sym_db.RegisterEnumDescriptor(_FIGHTRESULT)

FightResult = enum_type_wrapper.EnumTypeWrapper(_FIGHTRESULT)
NO_UPGRADE = 0
MUST_UPGARDE_APP = 1
SHOULD_UPGRADE_APP = 2
UPGRADE_RESOURCE = 3
G2X2 = 1
G4X4 = 2
UNKNOWN = 0
USA = 1
RUSSIA = 2
STAY = 1
MOVE = 2
RAID = 3
RAID_FAILURE = 4
STORM = 5
NORMAL = 1
ONLY_REST = 2
LEFT = 1
RIGHT = 2


DESCRIPTOR.enum_types_by_name['UpgradeType'] = _UPGRADETYPE
DESCRIPTOR.enum_types_by_name['GameType'] = _GAMETYPE
DESCRIPTOR.enum_types_by_name['ForceType'] = _FORCETYPE
DESCRIPTOR.enum_types_by_name['ForceMoveType'] = _FORCEMOVETYPE
DESCRIPTOR.enum_types_by_name['IslandType'] = _ISLANDTYPE
DESCRIPTOR.enum_types_by_name['FightResult'] = _FIGHTRESULT


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024com.box.island.protoB\010ConstantH\003'))
# @@protoc_insertion_point(module_scope)
